version: '3.8'

services:
  core:
    build:
      context: .
    environment:
      PORT: ${PORT}
      DB_URI: ${DB_URI}
      DB_NANE: ${DB_NANE}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      MEDIA_SERVICE_URL: ${MEDIA_SERVICE_URL}
    env_file:
      - .env
    expose:
      - "3000"
    networks:
      - ichgram-network

networks:
  ichgram-network:
    driver: bridge
    external: true
